walk_id_num: 4  # total quantity of walking motor drivers connected to can analyst 
steer_id_num: 4  # total quantity of steering motor drivers connected to can analyst 

encoder_s: 2500  # encoder line of steering motor
encoder_w: 2500  # encoder line of walking motor
frequency_multiplier: 4 
reduc_ratio_s: 220  # reduction ratio of steering motor
reduc_ratio_w: 20.15  # reduction ratio of walking motor
max_velocity: 1500  

walking_channel:
  chn1: 1  # front walking wheels
  chn2: 2  # rear walking wheels

steering_channel:
  chn1: 3  # front steering wheels
  chn2: 4  # rear steering wheels


motor_sign:
  fwl: 1  # front walking left
  fwr: 0  # front walking right
  rwl: 1  # rear walking left
  rwr: 0  # rear walking right
  fsl: 0  # front steering left
  fsr: 0  # front steering right
  rsl: 0  # rear steering left
  rsr: 0  # rear steering right


front_rear_track: 0.5  # length of mobile_base
left_right_track: 0.395  # width of mobile_base
wheel_radius:
